EXPERIMENT_NAME: 'hackathon/ConvNextUnet2d/baseline/base'
DATA:
  NUM_WORKERS: 8
  IN_CHANNELS: 3
  OUT_CHANNELS: 5
  MEAN_CENTER: True
  STANDARDIZE: True
MODEL:
  ARCHITECTURE: 'ConvNextUnet2d'
  CHECKPOINT_INTERVAL: 5
SOLVER:
  USE_AMP: False
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.0001
  NUM_EPOCHS: 40
  SCHEDULER: 'step'
  LR_MILESTONES: []
  LR_DECAY_STEPS: 20
  LR_DECAY_FACTOR: 0.9
  BATCH_SIZE_TRAIN: 16
  BATCH_SIZE_TEST: 16